### PR TITLE
Add spek test framework

### PR DESCRIPTION
**Pull request by dylanf**
In this PR I have added the spek test framework

http://spekframework.org/notes/1.0.html
http://spekframework.org/docs/latest/

Note that the spek intellij plugin does not work correctly because we are using JUnit 4 - so basically we need to run the tests from the command line

NB if a spek branch was created I could make the PR to that instead.

### CODE REVIEW

**Review by BenDave — APPROVED** [review]

**Comment by paucls** [comment]
Why do we need to use JUnit version 4?
I have a sample kata project with kotlin and spek that also works from the IDE here https://github.com/paucls/kotlin-spek-kata-seed 

spek

**Comment by dylanf** [comment]
spring-boot-test pulls in junit 4 - it may be possible to get it to use junit 5 but I didn't want to spend too much time potentially mucking up the ability to do integration tests.

note in the end I have wound up using straight junit 4 because I found that with the current setup spek was not working as expected (or at least as I expected).

**Comment by paucls** [comment]
No problem Dylan, I don't want either to make things more complicated at this stage.

**Review by paucls — APPROVED** [review]

**Comment by paucls** [comment]
the formatting of the file is off now

**Review by paucls — APPROVED** [review]

**Pull request merged**
